
### Hacettepe University Computer Engineering Department
#### BBM-409 Machine Learning Lab - Assignment 1
#### Detection of Fake News
##### Name/Surname: Furkan Çağlar Gülmez
##### Id: 21527027 
##### Advisors: Dr. Aykut Erdem, T.A. Necva Bölücü




---

### Part I: Theory Questions

---

* **MLE**

-----

**a-)** Suppose you have N samples x1,x2.....xN from a univariate normal distribution with unknown mean μ and known variance σ2. Derive the MLE estimator for the mean μ.

*               

 _____ <img src="mle1.jpg" alt="drawing" width="500"/>

**b-)** Consider a dataset (xn, cn), n = 1, ..., N of binary attributes, xni ∈ 0, 1, i = 1, ..., D and associated class label cn. The number of datapoints from class c = 0 is denoted n0 and the number from class c = 1 is denoted n1. Estimate p(xi = 1|c) ≡ θic.


*         

_____ <img src="ml4.png" alt="drawing" width="500"/>

**c-)** Suppose that X is a discrete rrandom variable with the following probability mass function: where 0 ≤ θ ≤ 1 is a parameter. The following 10 independent ob- servations were taken from such a distribution: (3,0,2,1,3,2,1,0,2,1). What is the maximum likelihood estimate of θ.

*                   

_____ <img src="mle2.jpg" alt="drawing" width="500"/>

***

* **Naive Bayes**

---

A psychologist does a small survey on ’happiness’. Each respondent provides a vector with entries 1 or 0 corresponding to whether they answer ’yes’ to a question or ’no’, respectively. The question vector has attributes
x = (rich, married, healthy)
Thus, a response (1, 0, 1) would indicate that the respondent was ’rich’, ’unmarried’, ’healthy’. In addition, each respondent gives a value c = 1 if they are content with their lifestyle, and c = 0 if they are not. The following responses were obtained from people who claimed also to be ’content’: (1, 1, 1), (0, 0, 1), (1, 1, 0), (1, 0, 1) and for ’not content’: (0, 0, 0), (1, 0, 0), (0, 0, 1), (0, 1, 0), (0, 0, 0) .

* Using Naive Bayes, what is the probability that a person who is ’not rich’, ’married’ and ’healthy’ is ’content’?

    P(content) = 4/9     P(not_content) = 5/9
    P(content|0 1 1) = P(0 1 1|content) * P(content)
    P(not rich | content) = 1/4
    P(married | content) = 1/2

* What is the probability that a person who is ’not rich’ and ’married’ is ’content’? (That is, we do not know whether ot not they are ’healthy’.)

    P(health|content) = 3/4
    After the calculations that is above, 
    P(content | 0 1 1) = 1/24

---

## PART II: Detection of Fake News

***

### 1. Used Libraries

***

* **Sklearn**

Sklearn is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.

     Features:
     ['and', 'document', 'first', 'is', 'one', 
     'second', 'the', 'third', 'this'] 
     
    Converse mapping:
     [[0 1 1 1 0 0 1 0 1]
      [0 1 0 1 0 2 1 0 1]
      [1 0 0 0 1 0 1 1 0]
      [0 1 1 1 0 0 1 0 1]] 
      
    Feature Document's Index is: 1
    
     So that we see that, the word 'document' is repeated 
     three times which are line first, second and last one. 

* **Numpy**

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.
I used numpy when I calculate cosine similarity and pearson correlation of two vectors. 

    The resulting array is -> [1 3 2 3 1 2 4 1 3] 
    This array says each word's count in the document.
    For example:  X[ vectorizer.vocabulary_.get('document') ] 
    == X [ 1 ] which is 3, that means that there is three word 'document'
    in the document.

* **Math**

For basic logarithmic calculations, I used math library.

***

### Datasets, Filtering, Cleaning

* **clean_fake-Train.txt & clean_real-train.txt:** 

1298 fake news headlines (which mostly include headlines of articles classified as bi- ased etc.) and 1968 real news headlines, where the fake news headlines are from https://www.kaggle.com/mrisdal/fake-news/data and real news headlines are from https://www.kaggle.com/therohk/million-headlines have been compiled. Data is cleaned by removing words from fake news titles that are not a part of the headline, removing special characters from the headlines, and restricting real news headlines to those after October 2016 containing the word trump.

* **test.csv:** Dataset contains a new headline and its label to predict

* Firstly, I tried to write my own stemmer. Because nltk's stemmer is not enough for cleans prefix of words.
But then I realized that when we clean data, accuracy is decreased so that I gave up writing my own stemmer. 

When I did this filterings 8950 users and 25800 ratings remaining.

### Algorithm

* read() function reads file, takes file path as a parameter and return an array which holds all line, **each line is one string**
* I also read the file with nltk's snowball stemmer and lemmatizer but I realized that when I let the code lemmatize or stem accuracy is decreased. Then I decided not to use it. 

* create_vectorizer() function takes an array and an int value as parameters.
    * array is which is returned from read() function
    * int value is to decide unigram or bigram
    * if ngram == 1 perform unigram, if ngram == 2 perform bigram
* returns 
    * a numpy array which holds count of words 
    * dictionary which holds word's indexes in numpy array 

* parameters:
    * sentences_tuple  : test data to predict
    *            arr1  : real data train
    *            arr2  : fake data train
    *              d1  : fake data dictionary
    *              d2  : real data dictionary
    *       fake_freq  : (fake line count) / (fake + real)
    *       real_freq  : (real line count) / (fake + real)
    *           ngram  : if 1 -> unigram, if 2 -> bigram


* returns:
    * accuracy of trained model


* function basicaly calculates naive bayes with all words in news' headlines


---

### Approach

## Part 1
#### Understanding the data
The data-set consists of real and fake news headlines related to the recent U.S elections, with about 2000 real headline and about 1300 fake headlines. By looking at the number of word occurrences we see that the words used the most for both real and fake headlines are mostly similar. We can also see that many of those words are stop-words (”of”, ”for”, ”on” ... etc). I have listed below three examples that I believe will help in classifying the headlines as real or fake:

**Real Headlines' Words (Unigram)**


* korea    : 
    * Real Count: 62  
    * Fake Count: 0 
    * Rate: 1.000


* ban      : 
    * Real Count: 65  
    * Fake Count: 1 
    * Rate: 0.985


* trumps   : 
    * Real Count: 184 
    * Fake Count: 4 
    * Rate: 0.979


**Fake Headlines' Words (Unigram)**


* just     : 
    * Real Count: 8 
    * Fake Count: 67
    * Rate: 0.893


* you      : 
    * Real Count: 7 
    * Fake Count: 55 
    * Rate: 0.887


* hillary  : 
    * Real Count: 21 
    * Fake Count: 126 
    * Rate: 0.857


**Real Headlines' Words (Bigram)**


* north korea   : 
    * Real Count: 60 
    * Fake Count: 0 
    * Rate: 1.000


* donald trumps : 
    * Real Count: 73 
    * Fake Count: 1 
    * Rate: 0.986


* trump says    : 
    * Real Count: 84 
    * Fake Count: 12 
    * Rate: 0.875


**Fake Headlines' Words (Bigram)**


* hillary clinton : 
    * Real Count: 19 
    * Fake Count: 40 
    * Rate: 0.678


* trump to        : 
    * Real Count: 29 
    * Fake Count: 27 
    * Rate: 0.482


* trump and       :
    * Real Count: 33 
    * Fake Count: 28 
    * Rate: 0.459

## Part 3
#### (a) Analyzing effect of the words on prediction

* **real presence**

    * korea     : 0.9999984706460329 
    * travel    : 0.999998161452981
    * turnbull  : 0.9999979567576792 
    * australia : 0.9999963593007417
    * refugee   : 0.999995744141818
    * paris     : 0.9999957441414531
    * debate    : 0.9999948834115259 
    * tax       : 0.9999948834110846
    * congress  : 0.9999945147023779 
    * defends   : 0.9999945147023779


* **real absence**

    * star : 0.6022727278336234 
    * black : 0.6022727277070424
    * breaking : 0.6022727276231271
    * u: 0.60227272758131
    * soros : 0.6022727275395864
    * won : 0.6022727275395864
    * woman : 0.6022727274564178 
    * homeless : 0.6022727273736188
    * info : 0.6022727273323573
    * daily : 0.6022727272911872

* **fake presence**

    * star : 0.6503072189992896 
    * black : 0.613751194679261
    * breaking : 0.5849902550380285), 
    * u : 0.5689972950641514
    * soros : 0.5517624714313497 
    * won : 0.551762461072533
    * woman : 0.5129396870889822 
    * homeless : 0.4669787763834351
    * info : 0.44067670120589464 
    * daily : 0.41171181939951795

* **fake absence**

    * trump : 0.39782056097
    * donald : 0.39773751613
    * to : 0.397730715197426
    * trumps : 0.39772921604
    * in : 0.397729024883772
    * us : 0.397729017719476
    * on : 0.397728782919198
    * says : 0.3977287493500
    * of : 0.397728657084839
    * for : 0.39772865663446

* **As we see notice that some words presence have a bigger effect on classifying headline than the effect of words being absent.**

---

#### (b) Stopwords

**without stopwords the list is below**

* **real presence**

    * korea:  0.99999833027299      
    * travel:  0.999997992
    * turnbull: 0.99999776923       
    * australia: 0.9999960
    * refugee: 0.999995353595       
    * paris: 0.99999535359
    * debate: 0.9999944138877       
    * tax: 0.9999944138872
    * congress: 0.99999401134       
    * defends: 0.999994011

* **real absence**

    * star: 0.602272727919815       
    * black: 0.60227272778
    * breaking: 0.60227272768       
    * u: 0.602272727641606
    * won: 0.6022727275956004       
    * soros: 0.60227272759
    * woman: 0.60227272750389       
    * homeless: 0.60227272
    * info: 0.602272727367098       
    * daily: 0.60227272732
    
* **fake presence**

    * star: 0.669992714999326       
    * black: 0.63433831479
    * breaking: 0.60612716074       
    * u: 0.590378685282129
    * soros: 0.57335807383263      
    * won: 0.5733580635116
    * woman: 0.53482944641718       
    * homeless: 0.48887646,
    * info: 0.462411309851494       
    * daily: 0.43312440248

* **fake absence**

    * trump: 0.39782101324822       
    * donald: 0.3977376125
    * trumps: 0.3977292352835       
    * says: 0.397728763873
    * clinton: 0.397727954887       
    * election: 0.39772794
    * ban: 0.3977278461398317       
    * korea: 0.39772780133
    * north: 0.39772780128976       
    * president: 0.3977277

**It would make sense to remove stop words as they are necessary words used in all sentences and they do not add any value in determining if a headline is real or fake. On the other hand It would make sense to keep them, as they help in identifying relations between headlines. For example if fake headlines has some specific patterns related to those stop words, we can detect this pattern and it will help us categorize the headlines. This is especially useful if many of the headlines have the same origin.**

### Analysis of the Predictions & Accuracy Calculations

<img src="gg.png" alt="drawing" width="500"/>

* with no stemmer or lemmatizer accuracies:
    * unigram: 85.480
    * bigram : 81.800

* with snowballstemmer accuracies:
    * unigram: 79.754
    * bigram : 77.300

* with lemmatizer accuracies:
    * unigram: 79.141
    * bigram : 81.390

As it seen in the plot, this is why I decided not to use stemmer or lemmatizer.

### Resources

https://arxiv.org/pdf/1708.07104.pdf

https://stackoverflow.com

https://pythonmachinelearning.pro/text-classification-tutorial-with-naive-bayes/

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

https://stats.stackexchange.com

https://towardsdatascience.com/hacking-scikit-learns-vectorizers-9ef26a7170af

https://stackoverflow.com/questions/23850256/how-can-i-pass-a-preprocessor-to-tfidfvectorizer-sklearn-python